# Generated by Django 4.2.6 on 2023-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0005_room_on_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="on_main",
            field=models.BooleanField(default=False, verbose_name="Show on Main Page"),
        ),
    ]
