"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 3.2.22.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
if os.path.isfile('env.py'):
    import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['booking-hotel-a07bb3df7136.herokuapp.com',
                 '8000-codewizard-1-booking-hot-qqi7tjr8vx.us2.codeanyapp.com']

CSRF_TRUSTED_ORIGINS = [
    'https://8000-codewizard-1-booking-hot-qqi7tjr8vx.us2.codeanyapp.com',
    'https://127.0.0.1',
]

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hotel',
    'cloudinary_storage',
    'cloudinary',
    'crispy_forms',
    'mathfilters',
    'ckeditor_uploader',
    'django_ckeditor_5',
    'taggit',
    'anymail',
    'django_summernote',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'corsheaders',
]

SITE_ID = 1

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_EMAIL_VERIFICATION = 'none'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Strict'

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.parse(os.environ.get("DATABASE_URL"))
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# JAZZMIN_SETTINGS = {
#     'site_header': 'Booking Hotel',
#     # 'site_brand': 'The best site for choosing and booking hotels.',
#     # 'site_logo': '/images/logo.png',
#     # 'copyright': 'All Right Reserved 2023',
#     'welcome_sign': 'Welcome to "Booking Hotel", Login Now.',
#     'topmenu_links': [
#         {'name': 'Home', 'url': 'admin:index', 'permissions': ['auth.view_user']},
#         {'name': 'Company', 'url': '/admin/addons/company/'},
#         {'name': 'Users', 'url': '/admin/userauths/user/'},

#         {'model': 'auth.User'},
#     ],

#     'order_with_respect_to': [
#         'hotel',
#         'hotel.Hotel',
#         'hotel.Room',
#         'hotel.Booking',
#         'hotel.BookingDetail',
#         'hotel.Guest',
#         'hotel.RoomServices',
#         'userauths',
#         'addons',
#     ],

#     'icons': {
#         'admin.LogEntry': 'fas fa-file',
#         'auth': 'fas fa-users-cog',
#         'auth.User': 'fas fa-users',
#         'userauths.User': 'fas fa-user',
#         'userauths.Profile': 'fas fa-address-card',
#         'hotel.Hotel': 'fas fa-th',
#         'hotel.Booking': 'fas fa-calendar-week',
#         'hotel.BookingDetail': 'fas fa-calendar-alt',
#         'hotel.Guest': 'fas fa-user',
#         'hotel.Room': 'fas fa-bed',
#         'hotel.RoomServices': 'fas fa-user-cog',
#         'hotel.Notification': 'fas fa-bell',
#         'hotel.Bookmark': 'fas fa-heart',
#     },

#     'show_ui_builder': True,
# }


# JAZZMIN_UI_TWEAKS = {
#     'navbar_small_text': False,
#     'footer_small_text': False,
#     'body_small_text': True,
#     'brand_small_text': False,
#     'brand_colour': 'navbar-indigo',
#     'accent': 'accent-olive',
#     'navbar': 'navbar-indigo navbar-dark',
#     'no_navbar_border': False,
#     'navbar_fixed': False,
#     'layout_boxed': False,
#     'footer_fixed': False,
#     'sidebar_fixed': False,
#     'sidebar': 'sidebar-dark-indigo',
#     'sidebar_nav_small_text': False,
#     'sidebar_disable_expand': False,
#     'sidebar_nav_child_indent': False,
#     'sidebar_nav_compact_style': False,
#     'sidebar_nav_legacy_style': False,
#     'sidebar_nav_flat_style': False,
#     'theme': 'cyborg',
#     'dark_mode_theme': 'cyborg',
#     'button_classes': {
#         'warning': 'btn-warning',
#         'danger': 'btn-danger',
#         'success': 'btn-success',
#     }
# }
